-- Tavelli MVP Supabase schema
-- Run in Supabase SQL editor once per project.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.ai_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action_type text not null check (action_type in ('reply', 'summary', 'action', 'analysis')),
  description text not null,
  target_email text not null,
  timestamp timestamptz not null default timezone('utc', now()),
  ai_style text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ai_history_user_id_timestamp_idx
  on public.ai_history (user_id, timestamp desc);

create table if not exists public.last_ten_analysis (
  user_id uuid not null references auth.users(id) on delete cascade,
  account_id text not null,
  data jsonb not null,
  analyzed_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, account_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists user_settings_set_updated_at on public.user_settings;
create trigger user_settings_set_updated_at
before update on public.user_settings
for each row execute function public.set_updated_at();

drop trigger if exists last_ten_analysis_set_updated_at on public.last_ten_analysis;
create trigger last_ten_analysis_set_updated_at
before update on public.last_ten_analysis
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do update
    set
      email = excluded.email,
      full_name = coalesce(excluded.full_name, public.profiles.full_name),
      avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
      updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user_profile();

alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.ai_history enable row level security;
alter table public.last_ten_analysis enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "settings_select_own" on public.user_settings;
create policy "settings_select_own"
  on public.user_settings
  for select
  using (auth.uid() = user_id);

drop policy if exists "settings_insert_own" on public.user_settings;
create policy "settings_insert_own"
  on public.user_settings
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "settings_update_own" on public.user_settings;
create policy "settings_update_own"
  on public.user_settings
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "history_select_own" on public.ai_history;
create policy "history_select_own"
  on public.ai_history
  for select
  using (auth.uid() = user_id);

drop policy if exists "history_insert_own" on public.ai_history;
create policy "history_insert_own"
  on public.ai_history
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "history_update_own" on public.ai_history;
create policy "history_update_own"
  on public.ai_history
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "last_ten_select_own" on public.last_ten_analysis;
create policy "last_ten_select_own"
  on public.last_ten_analysis
  for select
  using (auth.uid() = user_id);

drop policy if exists "last_ten_insert_own" on public.last_ten_analysis;
create policy "last_ten_insert_own"
  on public.last_ten_analysis
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "last_ten_update_own" on public.last_ten_analysis;
create policy "last_ten_update_own"
  on public.last_ten_analysis
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update on public.user_settings to authenticated;
grant select, insert, update on public.ai_history to authenticated;
grant select, insert, update on public.last_ten_analysis to authenticated;
grant usage, select on sequence public.ai_history_id_seq to authenticated;
